service: notes-app-3

provider:
  name: aws
  # runtime: nodejs6.10
  runtime: nodejs12.x
  stage: dev
  region: ap-southeast-2

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'


# component: express
# name: express-starter

# inputs:
#   src: ./
